# Generated by Django 5.0.8 on 2024-08-18 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_city_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='alt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
