# Generated by Django 5.0.8 on 2024-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_vocabularylist_vocabularyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularylist',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cities',
            name='image_url2',
            field=models.URLField(default='LoremIpsum'),
        ),
        migrations.AddField(
            model_name='cities',
            name='image_url3',
            field=models.URLField(default='LoremIpsum'),
        ),
        migrations.AddField(
            model_name='cities',
            name='parag2',
            field=models.TextField(default='LoremIpsum'),
        ),
        migrations.AddField(
            model_name='cities',
            name='parag3',
            field=models.TextField(default='LoremIpsum'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='alt',
            field=models.TextField(default='LoremIpsum'),
        ),
    ]
